### ISSUE TITLE
Parameter sectioon is not expected, how are parameters passed

### ISSUE THREAD

**Issue by MihailSahatchiev** [aws-ia/taskcat#559]
taskcat test run

**To Reproduce**
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python3 get-pip.py --user
      - pip install --upgrade pip
      - pip3 install taskcat --user
      - taskcat --version
     - taskcat test run
error: ValidationError Additional properties are not allowed ('parameters' was unexpected)

github url of docs, i run it from ci folder in taskcat example folder https://github.com/MihailSahatchiev/TaskCat-example

**Comment by andrew-glenn** [comment]
You’re running into documentation lag. Apologies.

Quick and dirty example. Does not include all required options. Just enough to demonstrate parameters.

```
project:
  name: my-thing
  template: templates/foo.template.json
  parameters:
    ParamName: my-value
    OtherParam: other-value
```

Towards the bottom of the README is the schema for the config file.
