### ISSUE TITLE
Linter failed for AWS::CodeCommit::Repository.RepositoryTrigger with unknown error

### ISSUE THREAD

**Issue by TLaue** [aws-ia/taskcat#576]
I am using taskcat within one of your pipelines to validate our CFN templates. However now our template fails with the following error message during the linting step: 

[ERROR ] : Lint detected issues for test xxx.template.yml:
[ERROR  ] :     line 1 [0002] [Error processing rule on the template] Unknown exception while processing rule E3003:
                                                            'AWS::CodeCommit::Repository.RepositoryTrigger'
[ERROR  ] :     line 1 [0002] [Error processing rule on the template] Unknown exception while processing rule E3002:
                                                            'AWS::CodeCommit::Repository.RepositoryTrigger'

The failing template section looks like this:

 ```
 Repository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref AppName
      Triggers:
        - CustomData: !Sub '{"SecretArnDev": "${SecretDev}","SecretsManagerKey": "${SecretsManagerKey.Arn}","AppName": "${AppName}","BuildImageName": "${BuildImageName}","ArtifactBucket": "${ArtifactBucket}","ArtifactBucketKeyArn": "${ArtifactBucketKeyArn}","SamTranslationBucket": "${SamTranslationBucket}","PipelineServiceRoleArn": "${PipelineServiceRoleArn}","DevAwsAccountId": "${DevAwsAccountId}", "TemplateURL": "${PipelineTemplateURL}"}'
        - DestinationArn: !Ref DynamicPipelineMakerLambdaArn
          Events:
            - createReference
            - deleteReference
          Name: Create or delete dynamic pipeline for new branch
```

I am using the taskcat version 0.9.18 and can reproduce this problem locally on my computer as well as on AWS CodeBuild. 

One additional side note: cfn-lint itself does not complain when being used as standalone tool but taskcat does not accept this template section.
