### ISSUE TITLE
ClientError An error occurred (IllegalLocationConstraintException) when calling the ListObjectsV2 operation: The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to

### ISSUE THREAD

**Issue by alucard001** [aws-ia/taskcat#801]
**Describe the bug**
Got an error with message below:

ClientError An error occurred (IllegalLocationConstraintException) when calling the ListObjectsV2 operation: The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to

**To Reproduce**
Docker command: 
`docker run --rm --mount type=bind,src=/my-source/cloudformation,target=/root --workdir /root taskcat/taskcat taskcat test run`

Within `/my-source/cloudformation`, directories are listed below:

/root/.aws/configure
```
[default]
aws_access_key_id=my_key
aws_secret_access_key=my_secret
```
/root/.aws/config
```
[default]
region=ap-east-1
output=text
```

/root/.taskcat.yml
```
project:
  name: opensearch
  package_lambda: false
  s3_bucket: my-s3-bucket-in-ap-east-1
  shorten_stack_name: true
  auth:
    default: default
  regions:
    - ap-east-1
tests:
  ossetup:
    stack_name: opensearch-setup
    template: /root/cf-OpenSearchServer.yml
```
Result Output:
```
version 0.9.39
Not in terminal, reprint now using normal build-in print function.

[INFO   ] : Linting passed for file: /root/cf-OpenSearchServer.yml
[WARN   ] : No stacks were created... skipping cleanup.
[ERROR  ] : ClientError An error occurred (IllegalLocationConstraintException) when calling the ListObjectsV2 operation: The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to.
```

**Version (Please make sure you are running the latest version of taskcat)
 - version 0.9.39

 Note: Python Version (python3 required)

**Additional context**
I've researched this problem but not sure how to fix this.  Here are the references:
- https://stackoverflow.com/questions/58143279/aws-cli-aws-s3-presign-does-not-work-for-ap-east-1-hong-kong-region-locatio
- https://stackoverflow.com/questions/56993266/illegallocationconstraintexception-on-cloudfront-for-s3
- https://github.com/aws/aws-cli/issues/4445

Please help.  Thank you very much in advance for your help.
